name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies (manual)
      run: |
        pip install selenium
        pip install pytest
        pip install allure-pytest
        pip install requests

    - name: Run tests with pytest
      run: pytest --alluredir=reports/allure-results
